# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: casino.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='casino.proto',
  package='casinoserver',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x63\x61sino.proto\x12\x0c\x63\x61sinoserver\"\xa2\x01\n\x11SentNoticeRequest\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\t\x12\r\n\x05\x61sset\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x04\x12\x14\n\x0c\x66\x65\x65_asset_id\x18\x04 \x01(\t\x12\x11\n\tfee_asset\x18\x05 \x01(\t\x12\x12\n\nfee_amount\x18\x06 \x01(\x04\x12\x11\n\tblock_num\x18\x07 \x01(\x04\x12\x0c\n\x04memo\x18\x08 \x01(\t\"\x11\n\x0fSentNoticeReply\"h\n\x14ReceiveNoticeRequest\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\t\x12\r\n\x05\x61sset\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x04\x12\x11\n\tblock_num\x18\x04 \x01(\x04\x12\x0c\n\x04memo\x18\x05 \x01(\t\"\x14\n\x12ReceiveNoticeReply2\xb1\x01\n\x06\x43\x61sino\x12N\n\nSentNotice\x12\x1f.casinoserver.SentNoticeRequest\x1a\x1d.casinoserver.SentNoticeReply\"\x00\x12W\n\rReceiveNotice\x12\".casinoserver.ReceiveNoticeRequest\x1a .casinoserver.ReceiveNoticeReply\"\x00\x62\x06proto3')
)




_SENTNOTICEREQUEST = _descriptor.Descriptor(
  name='SentNoticeRequest',
  full_name='casinoserver.SentNoticeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='asset_id', full_name='casinoserver.SentNoticeRequest.asset_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asset', full_name='casinoserver.SentNoticeRequest.asset', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='casinoserver.SentNoticeRequest.amount', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fee_asset_id', full_name='casinoserver.SentNoticeRequest.fee_asset_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fee_asset', full_name='casinoserver.SentNoticeRequest.fee_asset', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fee_amount', full_name='casinoserver.SentNoticeRequest.fee_amount', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_num', full_name='casinoserver.SentNoticeRequest.block_num', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memo', full_name='casinoserver.SentNoticeRequest.memo', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=193,
)


_SENTNOTICEREPLY = _descriptor.Descriptor(
  name='SentNoticeReply',
  full_name='casinoserver.SentNoticeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=212,
)


_RECEIVENOTICEREQUEST = _descriptor.Descriptor(
  name='ReceiveNoticeRequest',
  full_name='casinoserver.ReceiveNoticeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='asset_id', full_name='casinoserver.ReceiveNoticeRequest.asset_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asset', full_name='casinoserver.ReceiveNoticeRequest.asset', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='casinoserver.ReceiveNoticeRequest.amount', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_num', full_name='casinoserver.ReceiveNoticeRequest.block_num', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memo', full_name='casinoserver.ReceiveNoticeRequest.memo', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=318,
)


_RECEIVENOTICEREPLY = _descriptor.Descriptor(
  name='ReceiveNoticeReply',
  full_name='casinoserver.ReceiveNoticeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=340,
)

DESCRIPTOR.message_types_by_name['SentNoticeRequest'] = _SENTNOTICEREQUEST
DESCRIPTOR.message_types_by_name['SentNoticeReply'] = _SENTNOTICEREPLY
DESCRIPTOR.message_types_by_name['ReceiveNoticeRequest'] = _RECEIVENOTICEREQUEST
DESCRIPTOR.message_types_by_name['ReceiveNoticeReply'] = _RECEIVENOTICEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SentNoticeRequest = _reflection.GeneratedProtocolMessageType('SentNoticeRequest', (_message.Message,), dict(
  DESCRIPTOR = _SENTNOTICEREQUEST,
  __module__ = 'casino_pb2'
  # @@protoc_insertion_point(class_scope:casinoserver.SentNoticeRequest)
  ))
_sym_db.RegisterMessage(SentNoticeRequest)

SentNoticeReply = _reflection.GeneratedProtocolMessageType('SentNoticeReply', (_message.Message,), dict(
  DESCRIPTOR = _SENTNOTICEREPLY,
  __module__ = 'casino_pb2'
  # @@protoc_insertion_point(class_scope:casinoserver.SentNoticeReply)
  ))
_sym_db.RegisterMessage(SentNoticeReply)

ReceiveNoticeRequest = _reflection.GeneratedProtocolMessageType('ReceiveNoticeRequest', (_message.Message,), dict(
  DESCRIPTOR = _RECEIVENOTICEREQUEST,
  __module__ = 'casino_pb2'
  # @@protoc_insertion_point(class_scope:casinoserver.ReceiveNoticeRequest)
  ))
_sym_db.RegisterMessage(ReceiveNoticeRequest)

ReceiveNoticeReply = _reflection.GeneratedProtocolMessageType('ReceiveNoticeReply', (_message.Message,), dict(
  DESCRIPTOR = _RECEIVENOTICEREPLY,
  __module__ = 'casino_pb2'
  # @@protoc_insertion_point(class_scope:casinoserver.ReceiveNoticeReply)
  ))
_sym_db.RegisterMessage(ReceiveNoticeReply)



_CASINO = _descriptor.ServiceDescriptor(
  name='Casino',
  full_name='casinoserver.Casino',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=343,
  serialized_end=520,
  methods=[
  _descriptor.MethodDescriptor(
    name='SentNotice',
    full_name='casinoserver.Casino.SentNotice',
    index=0,
    containing_service=None,
    input_type=_SENTNOTICEREQUEST,
    output_type=_SENTNOTICEREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReceiveNotice',
    full_name='casinoserver.Casino.ReceiveNotice',
    index=1,
    containing_service=None,
    input_type=_RECEIVENOTICEREQUEST,
    output_type=_RECEIVENOTICEREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CASINO)

DESCRIPTOR.services_by_name['Casino'] = _CASINO

# @@protoc_insertion_point(module_scope)
