# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wallet.proto',
  package='walletoserver',
  syntax='proto3',
  serialized_pb=_b('\n\x0cwallet.proto\x12\rwalletoserver\"$\n\x03\x46\x65\x65\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\t\x12\x0b\n\x03\x66\x65\x65\x18\x02 \x01(\r\"\x1f\n\rGetFeeRequest\x12\x0e\n\x06\x61ssets\x18\x01 \x03(\t\"L\n\x0cGetFreeReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12 \n\x04\x66\x65\x65s\x18\x03 \x03(\x0b\x32\x12.walletoserver.Fee\"M\n\x0fTransferRequest\x12\n\n\x02to\x18\x01 \x01(\t\x12\x10\n\x08\x61sset_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\r\x12\x0c\n\x04memo\x18\x04 \x01(\t\"+\n\rTransferReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2\x9c\x01\n\x06Wallet\x12\x46\n\x07GetFees\x12\x1c.walletoserver.GetFeeRequest\x1a\x1b.walletoserver.GetFreeReply\"\x00\x12J\n\x08Transfer\x12\x1e.walletoserver.TransferRequest\x1a\x1c.walletoserver.TransferReply\"\x00\x62\x06proto3')
)




_FEE = _descriptor.Descriptor(
  name='Fee',
  full_name='walletoserver.Fee',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='asset_id', full_name='walletoserver.Fee.asset_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fee', full_name='walletoserver.Fee.fee', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=67,
)


_GETFEEREQUEST = _descriptor.Descriptor(
  name='GetFeeRequest',
  full_name='walletoserver.GetFeeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='assets', full_name='walletoserver.GetFeeRequest.assets', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=100,
)


_GETFREEREPLY = _descriptor.Descriptor(
  name='GetFreeReply',
  full_name='walletoserver.GetFreeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='walletoserver.GetFreeReply.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason', full_name='walletoserver.GetFreeReply.reason', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fees', full_name='walletoserver.GetFreeReply.fees', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=178,
)


_TRANSFERREQUEST = _descriptor.Descriptor(
  name='TransferRequest',
  full_name='walletoserver.TransferRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='to', full_name='walletoserver.TransferRequest.to', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asset_id', full_name='walletoserver.TransferRequest.asset_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='walletoserver.TransferRequest.amount', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memo', full_name='walletoserver.TransferRequest.memo', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=257,
)


_TRANSFERREPLY = _descriptor.Descriptor(
  name='TransferReply',
  full_name='walletoserver.TransferReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='walletoserver.TransferReply.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason', full_name='walletoserver.TransferReply.reason', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=302,
)

_GETFREEREPLY.fields_by_name['fees'].message_type = _FEE
DESCRIPTOR.message_types_by_name['Fee'] = _FEE
DESCRIPTOR.message_types_by_name['GetFeeRequest'] = _GETFEEREQUEST
DESCRIPTOR.message_types_by_name['GetFreeReply'] = _GETFREEREPLY
DESCRIPTOR.message_types_by_name['TransferRequest'] = _TRANSFERREQUEST
DESCRIPTOR.message_types_by_name['TransferReply'] = _TRANSFERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Fee = _reflection.GeneratedProtocolMessageType('Fee', (_message.Message,), dict(
  DESCRIPTOR = _FEE,
  __module__ = 'wallet_pb2'
  # @@protoc_insertion_point(class_scope:walletoserver.Fee)
  ))
_sym_db.RegisterMessage(Fee)

GetFeeRequest = _reflection.GeneratedProtocolMessageType('GetFeeRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETFEEREQUEST,
  __module__ = 'wallet_pb2'
  # @@protoc_insertion_point(class_scope:walletoserver.GetFeeRequest)
  ))
_sym_db.RegisterMessage(GetFeeRequest)

GetFreeReply = _reflection.GeneratedProtocolMessageType('GetFreeReply', (_message.Message,), dict(
  DESCRIPTOR = _GETFREEREPLY,
  __module__ = 'wallet_pb2'
  # @@protoc_insertion_point(class_scope:walletoserver.GetFreeReply)
  ))
_sym_db.RegisterMessage(GetFreeReply)

TransferRequest = _reflection.GeneratedProtocolMessageType('TransferRequest', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFERREQUEST,
  __module__ = 'wallet_pb2'
  # @@protoc_insertion_point(class_scope:walletoserver.TransferRequest)
  ))
_sym_db.RegisterMessage(TransferRequest)

TransferReply = _reflection.GeneratedProtocolMessageType('TransferReply', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFERREPLY,
  __module__ = 'wallet_pb2'
  # @@protoc_insertion_point(class_scope:walletoserver.TransferReply)
  ))
_sym_db.RegisterMessage(TransferReply)



_WALLET = _descriptor.ServiceDescriptor(
  name='Wallet',
  full_name='walletoserver.Wallet',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=305,
  serialized_end=461,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFees',
    full_name='walletoserver.Wallet.GetFees',
    index=0,
    containing_service=None,
    input_type=_GETFEEREQUEST,
    output_type=_GETFREEREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Transfer',
    full_name='walletoserver.Wallet.Transfer',
    index=1,
    containing_service=None,
    input_type=_TRANSFERREQUEST,
    output_type=_TRANSFERREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WALLET)

DESCRIPTOR.services_by_name['Wallet'] = _WALLET

# @@protoc_insertion_point(module_scope)
